[pytest]
addopts = 
    --cov=search_module 
    --cov=recomendation_module/src
    --cov-config=search_module/.coveragerc 
    --cov-report=term-missing

testpaths =
    search_module/tests
    recomendation_module/tests

env_files =
    .env

filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
